//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagerCarEntities2 : DbContext
    {
        public ManagerCarEntities2()
            : base("name=ManagerCarEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> address { get; set; }
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<branch> branch { get; set; }
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<distributor> distributor { get; set; }
        public virtual DbSet<staff> staff { get; set; }
    }
}
