//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime brithday { get; set; }
        public string cart_number { get; set; }
        public int salary { get; set; }
        public Nullable<int> distributorId { get; set; }
        public Nullable<int> carId { get; set; }
        public Nullable<int> addressId { get; set; }
    
        public virtual address address { get; set; }
        public virtual car car { get; set; }
        public virtual distributor distributor { get; set; }
    }
}
